services:
  postgres:
    image: postgres:15
    container_name: postgres-auth
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
